/**
 * walmart
 * microservicio de usuarios
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ResponseProductoResponse { 
    _id?: string;
    id?: number;
    brand?: string;
    description?: string;
    image?: string;
    price?: number;
}